name: Integration-Test

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  itest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        java: [ '11' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: sbt
#      - run: sbt it:test
#        shell: bash
